on:
  push:
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  

    - name: Restore Dependencies
      run: dotnet restore WebGoat/WebGoat.NET.csproj

    - name: Build Project
      run: dotnet build WebGoat/WebGoat.NET.csproj --configuration Debug
    
